ADD_PROJECTILE ~%MOD_FOLDER%/bardsong/c0bardso.PRO~ ~C0 Bardsong~

ACTION_FOR_EACH invisible_area IN INAREANP INAREA INAREASM BIGNAREA INAREAPA BEGIN
    COPY_EXISTING ~%invisible_area%.pro~ ~OVERRIDE~
     WRITE_BYTE 0x21a 0
  END

COPY ~%MOD_FOLDER%/bardsong/c0bardsx.spl~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Bard Song Ready~) END
COPY ~%MOD_FOLDER%/bardsong/c0brdef1.bam~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0brdef1.vvc~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0bardso.wav~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singin.eff~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singin.spl~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Singing Bard Song~) END
COPY ~%MOD_FOLDER%/bardsong/c0singi2.eff~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singi2.spl~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singi2.spl~ OVERRIDE

ACTION_IF FILE_EXISTS_IN_GAME ~C0BWHL8.spl~ THEN BEGIN
COPY_EXISTING ~C0BWHL3.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL4.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL5.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL8.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 99 parameter1 = 130 END
END

// BARD

ACTION_IF FILE_EXISTS_IN_GAME ~FJBARDB.SPL~ THEN BEGIN
COPY_EXISTING ~FJBARDB.SPL~ ~OVERRIDE/FJBARDB3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = FJBARDB resource = FJBARDB3 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/FJBARDB.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = FJBARDB END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/FJBARDB.EFF~
WRITE_ASCII 0x30 FJBARDB3
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPCL920A.SPL~ THEN BEGIN
COPY_EXISTING ~SPCL920A.SPL~ ~OVERRIDE/SPCL920B.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL920A resource = SPCL920B END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL920A.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL920A END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL920A END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL920A.EFF~
WRITE_ASCII 0x30 SPCL920B
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD1.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD1.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL120.SPL~ ~OVERRIDE/SPCL120C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL120 resource = SPCL120C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL120.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL120 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL120 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL120.EFF~
WRITE_ASCII 0x30 SPCL120C
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD2.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD2.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 2 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL115.SPL~ ~OVERRIDE/SPCL115C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL115 resource = SPCL115C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL115.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL115 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL115 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL115.EFF~
WRITE_ASCII 0x30 SPCL115C
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD3.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD3.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 3 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL116.SPL~ ~OVERRIDE/SPCL116C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL116 resource = SPCL116C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL116.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL116 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL116 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL116.EFF~
WRITE_ASCII 0x30 SPCL116C
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD4.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD4.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 4 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL117.SPL~ ~OVERRIDE/SPCL117C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL117 resource = SPCL117C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL117.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL117 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL117 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL117.EFF~
WRITE_ASCII 0x30 SPCL117C
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD5.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD5.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 5 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL118.SPL~ ~OVERRIDE/SPCL118C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL118 resource = SPCL118C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL118.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL118 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL118 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL118.EFF~
WRITE_ASCII 0x30 SPCL118C
END

ACTION_IF FILE_EXISTS_IN_GAME ~#BARD6.SPL~ THEN BEGIN
COPY_EXISTING ~#BARD6.SPL~ ~OVERRIDE~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 6 timing = 1 STR_VAR resource = C0IWSONG END
COPY_EXISTING ~SPCL119.SPL~ ~OVERRIDE/SPCL119C.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL119 resource = SPCL119C END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 272 STR_VAR special = 0 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL119.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL119 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL119 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL119.EFF~
WRITE_ASCII 0x30 SPCL119C
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPCL920A.SPL~ THEN BEGIN
COPY_EXISTING ~SPCL920.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name TRUECLASS

OUTER_SPRINT bard_song fjbardb

OUTER_SPRINT hla_song spcl920A

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF GAME_IS ~IWDEE~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur-iwd.baf~ EVAL
END

// BLADE

ACTION_IF FILE_EXISTS_IN_GAME ~FJBLADEB.SPL~ THEN BEGIN
COPY_EXISTING ~FJBLADEB.SPL~ ~OVERRIDE/FJBLADB3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = FJBLADEB resource = FJBLADB3 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/FJBLADEB.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = FJBLADEB END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = FJBLADEB END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/FJBLADEB.EFF~
WRITE_ASCII 0x30 FJBLADB3
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0BLDSO.SPL~ THEN BEGIN
COPY_EXISTING ~C0BLDSO.SPL~ ~OVERRIDE/C0BLDSO3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0BLDSO resource = C0BLDSO3 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0BLDSO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0BLDSO END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0BLDSO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0BLDSO.EFF~
WRITE_ASCII 0x30 C0BLDSO3
END

// JESTER

ACTION_IF FILE_EXISTS_IN_GAME ~SPCL751A.SPL~ THEN BEGIN
COPY_EXISTING ~SPCL751A.SPL~ ~OVERRIDE/SPCL751B.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL751A resource = SPCL751B END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL751A.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL751A END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL751A END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL751A.EFF~
WRITE_ASCII 0x30 SPCL751B
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0JES03A.SPL~ THEN BEGIN
COPY_EXISTING ~C0JES03A.SPL~ ~OVERRIDE/C0JES03B.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0JES03A resource = C0JES03B END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0JES03A.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0JES03A END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0JES03A END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0JES03A.EFF~
WRITE_ASCII 0x30 C0JES03B
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0JES03.SPL~ THEN BEGIN
COPY_EXISTING ~C0JES03.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name JESTER

OUTER_SPRINT bard_song SPCL751A

ACTION_IF FILE_EXISTS_IN_GAME ~C0JES03A.SPL~ THEN BEGIN
OUTER_SPRINT hla_song C0JES03A
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

// SKALD

ACTION_IF FILE_EXISTS_IN_GAME ~SPCL542A.SPL~ THEN BEGIN
COPY_EXISTING ~SPCL542A.SPL~ ~OVERRIDE/SPCL542B.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = SPCL542A resource = SPCL542B END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/SPCL542A.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = SPCL542A END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = SPCL542A END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/SPCL542A.EFF~
WRITE_ASCII 0x30 SPCL542B
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0SKD02A.SPL~ THEN BEGIN
COPY_EXISTING ~C0SKD02A.SPL~ ~OVERRIDE/C0SKD02B.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0SKD02A resource = C0SKD02B END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0SKD02A.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0SKD02A END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0SKD02A END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0SKD02A.EFF~
WRITE_ASCII 0x30 C0SKD02B
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0SKD02.SPL~ THEN BEGIN
COPY_EXISTING ~C0SKD02.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name SKALD

OUTER_SPRINT bard_song SPCL542A

ACTION_IF FILE_EXISTS_IN_GAME ~C0SKD02A.SPL~ THEN BEGIN
OUTER_SPRINT hla_song C0SKD02A
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

// Lorekeeper

ACTION_IF FILE_EXISTS_IN_GAME ~X3RPKIT2.SPL~ THEN BEGIN
COPY_EXISTING ~X3RPKIT2.SPL~ ~OVERRIDE/X3RPKIT5.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = X3RPKIT2 resource = X3RPKIT5 END
COPY_EXISTING ~X3RHLAS.SPL~ ~OVERRIDE/X3RHLAS2.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = X3RHLAS resource = X3RHLAS2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/X3RPKIT2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = X3RPKIT2 END
  WRITE_ASCIIT 0x10 X3FLUTE
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = X3RPKIT2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/X3RPKIT2.EFF~
WRITE_ASCII 0x30 X3RPKIT5
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/X3RHLAS.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = X3RHLAS END
  WRITE_ASCIIT 0x10 X3FLUTE
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = X3RHLAS END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/X3RHLAS.EFF~
WRITE_ASCII 0x30 X3RHLAS2

ACTION_IF FILE_EXISTS_IN_GAME ~X3RHLA.SPL~ THEN BEGIN
COPY_EXISTING ~X3RHLA.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name X3Bard

OUTER_SPRINT bard_song X3RPKIT2

OUTER_SPRINT hla_song X3RHLAS

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// NIGHTSINGER

ACTION_IF FILE_EXISTS_IN_GAME ~C0SASONG.SPL~ THEN BEGIN
COPY_EXISTING ~C0SASONG.SPL~ ~OVERRIDE/C0SASON3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0SASONG resource = C0SASON3 END
COPY_EXISTING ~C0SASON2.SPL~ ~OVERRIDE/C0SASON4.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0SASON2 resource = C0SASON4 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0SASONG.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0SASONG END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0SASONG END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0SASONG.EFF~
WRITE_ASCII 0x30 C0SASON3
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0SASON2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0SASON2 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0SASON2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0SASON2.EFF~
WRITE_ASCII 0x30 C0SASON4

ACTION_IF FILE_EXISTS_IN_GAME ~C0SAHLAC.SPL~ THEN BEGIN
COPY_EXISTING ~C0SAHLAC.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0SABARD

OUTER_SPRINT bard_song C0SASONG

OUTER_SPRINT hla_song C0SASON2

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// ABETTOR

ACTION_IF FILE_EXISTS_IN_GAME ~C0ABETSO.SPL~ THEN BEGIN
COPY_EXISTING ~C0ABETSO.SPL~ ~OVERRIDE/C0ABETS3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0ABETSO resource = C0ABETS3 END
COPY_EXISTING ~C0ABETS2.SPL~ ~OVERRIDE/C0ABETS4.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0ABETS2 resource = C0ABETS4 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0ABETSO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0ABETSO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0ABETSO.EFF~
WRITE_ASCII 0x30 C0ABETS3
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0ABETS2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0ABETS2 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0ABETSO END
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0ABETS2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0ABETS2.EFF~
WRITE_ASCII 0x30 C0ABETS4

ACTION_IF FILE_EXISTS_IN_GAME ~C0ABETHL.SPL~ THEN BEGIN
COPY_EXISTING ~C0ABETHL.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0ABETT

OUTER_SPRINT bard_song C0ABETSO

OUTER_SPRINT hla_song C0ABETS2

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// DARKBLOOM

ACTION_IF FILE_EXISTS_IN_GAME ~C0BDD#SO.SPL~ THEN BEGIN
COPY_EXISTING ~C0BDD#SO.SPL~ ~OVERRIDE/C0BDD#S3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0BDD#SO resource = C0BDD#S3 END
COPY_EXISTING ~C0BDD#S2.SPL~ ~OVERRIDE/C0BDD#S4.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0BDD#S2 resource = C0BDD#S4 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0BDD#SO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0BDD#SO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0BDD#SO.EFF~
WRITE_ASCII 0x30 C0BDD#S3
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0BDD#S2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0BDD#S2 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0BDD#SO END
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0BDD#S2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0BDD#S2.EFF~
WRITE_ASCII 0x30 C0BDD#S4

ACTION_IF FILE_EXISTS_IN_GAME ~C0BDDHL.SPL~ THEN BEGIN
COPY_EXISTING ~C0BDDHL.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0BDD

OUTER_SPRINT bard_song C0BDD#SO

OUTER_SPRINT hla_song C0BDD#S2

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// KAPELLMEISTER

ACTION_IF FILE_EXISTS_IN_GAME ~C0KM#SO.SPL~ THEN BEGIN
COPY_EXISTING ~C0KM#SO.SPL~ ~OVERRIDE/C0KM#SOA.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0KM#SO resource = C0KM#SOA END
COPY_EXISTING ~C0KM#SOH.SPL~ ~OVERRIDE/C0KM#SOB.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0KM#SOH resource = C0KM#SOB END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0KM#SO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0KM#SO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0KM#SO.EFF~
WRITE_ASCII 0x30 C0KM#SOA
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0KM#SOH.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0KM#SOH END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0KM#SO END
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0KM#SOH END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0KM#SOH.EFF~
WRITE_ASCII 0x30 C0KM#SOB

ACTION_IF FILE_EXISTS_IN_GAME ~C0KM#H4.SPL~ THEN BEGIN
COPY_EXISTING ~C0KM#H4.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0_KAPELLMEISTER

OUTER_SPRINT bard_song C0KM#SO

OUTER_SPRINT hla_song C0KM#SOH

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// STORM DRUMMER

ACTION_IF FILE_EXISTS_IN_GAME ~C0SDRUSO.SPL~ THEN BEGIN
COPY_EXISTING ~C0SDRUSO.SPL~ ~OVERRIDE/C0SDRUS3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0SDRUS resource = C0SDRUS3 END
COPY_EXISTING ~C0SDRUS2.SPL~ ~OVERRIDE/C0SDRUS4.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0SDRUS2 resource = C0SDRUS4 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0SDRUSO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0SDRUSO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0SDRUSO.EFF~
WRITE_ASCII 0x30 C0SDRUS3
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0SDRUS2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0SDRUS2 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0SDRUSO END
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0SDRUS2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0SDRUS2.EFF~
WRITE_ASCII 0x30 C0SDRUS4

ACTION_IF FILE_EXISTS_IN_GAME ~C0SDRUHL.SPL~ THEN BEGIN
COPY_EXISTING ~C0SDRUHL.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0SDRUM

OUTER_SPRINT bard_song C0SDRUSO

OUTER_SPRINT hla_song C0SDRUS2

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

// TROUBADOUR

ACTION_IF FILE_EXISTS_IN_GAME ~C0TRBSO.SPL~ THEN BEGIN
COPY_EXISTING ~C0TRBSO.SPL~ ~OVERRIDE/C0TRBSO3.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0TRBSO resource = C0TRBSO3 END
COPY_EXISTING ~C0TRBSO2.SPL~ ~OVERRIDE/C0TRBSO4.SPL~
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = C0TRBSO2 resource = C0TRBSO4 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0TRBSO.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0TRBSO END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0TRBSO.EFF~
WRITE_ASCII 0x30 C0TRBSO3
COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/C0TRBSO2.SPL~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
  LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = C0TRBSO2 END
COPY_EXISTING ~c0singi2.SPL~ ~OVERRIDE~
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0TRBSO END
  LPF CLONE_EFFECT INT_VAR match_opcode = 321 silent = 1 STR_VAR match_resource = fjbardb resource = C0TRBSO2 END
COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/C0TRBSO2.EFF~
WRITE_ASCII 0x30 C0TRBSO4

ACTION_IF FILE_EXISTS_IN_GAME ~C0TRBHL.SPL~ THEN BEGIN
COPY_EXISTING ~C0TRBHL.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 2 parameter1 = 1 timing = 1 STR_VAR resource = C0BWHLAB END
END

OUTER_SPRINT kit_name C0TRB

OUTER_SPRINT bard_song C0TRBSO

OUTER_SPRINT hla_song C0TRBSO2

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/bardsong/script/baldur.baf~ EVAL
END
END

COPY_EXISTING ~enginest.2da~ ~override~
  COUNT_2DA_ROWS 2 rows
  FOR (row = 0 ; row < rows ; ++row) BEGIN
    READ_2DA_ENTRY row 0 2 entry
    PATCH_IF (("%entry%" STRING_COMPARE_CASE "STRREF_FEEDBACK_BATTLESONGBEGIN"      = 0) OR
              ("%entry%" STRING_COMPARE_CASE "STRREF_FEEDBACK_BATTLESONGEND"   		= 0)) BEGIN
      FOR (col = 1; col < 2 ; ++col) BEGIN
        SET_2DA_ENTRY row col 2 0
      END
    END
  END
  PRETTY_PRINT_2DA
  BUT_ONLY
  
///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//BARD
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "BARD" BEGIN
          READ_2DA_ENTRY index 4 col_count BARD_desc
          SPRINT old_BARD_eff ~While active, the Bard Song has the following effects:
  Restore morale to its average value
  Remove Fear
  Protection From Fear~
          SPRINT new_BARD_eff ~While active, the Bard Song has the following effects, improving with level:
  1st level: +1 Luck, immunity to fear and morale failure
  15th level: +2 Luck, immunity to fear and morale failure
  20th level: +3 Luck, immunity to fear and morale failure
~
          SPRINT old_BARD ~– May use Bard Song ability~
          SPRINT new_BARD ~– May use Bard Song ability.
          
REPLACE_ME_BARDSONG~
          SPRINT old_BARD2 ~REPLACE_ME_BARDSONG~
          SPRINT new_BARD2 ~BARD SONG: The Bard's Song may be used an unlimited number of times, and lasts for 6 rounds + 1 round per 5 levels gained. The Bard Song has a cooldown of 1 turn before it may be used again.~
          GET_STRREF %BARD_desc% BARD_text
          INNER_PATCH_SAVE BARD_text ~%BARD_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_BARD2%~ ~~
            REPLACE_TEXTUALLY ~%old_BARD%~ ~%new_BARD%~
            REPLACE_TEXTUALLY ~%old_BARD_eff%~ ~%new_BARD_eff%~
            REPLACE_TEXTUALLY ~%old_BARD2%~ ~%new_BARD2%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%BARD_desc%~ ~%BARD_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all spell files
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 200 parameter1 = 110 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 300 parameter1 = 120 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 400 parameter1 = 130 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 500 parameter1 = 140 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 600 parameter1 = 150 END
BUT_ONLY


COPY_EXISTING_REGEXP GLOB ~^.+\.bcs~ ~override~ //Parse through all dlg files
                DECOMPILE_AND_PATCH BEGIN
                    REPLACE_TEXTUALLY ~!ModalState(BATTLESONG)~ ~!CheckSpellState(Myself,BARD_SONG)~ //Replace trigger respecting OR and !
                END
                DECOMPILE_AND_PATCH BEGIN
                    //Recommended by refactor trigger to fix whitespace
                END

        BUT_ONLY
        