ADD_PROJECTILE ~%MOD_FOLDER%/bardsong/c0bardso.PRO~ ~C0 Bardsong~

ACTION_FOR_EACH invisible_area IN INAREANP INAREA INAREASM BIGNAREA INAREAPA BEGIN
    COPY_EXISTING ~%invisible_area%.pro~ ~OVERRIDE~
     WRITE_BYTE 0x21a 0
  END

COPY ~%MOD_FOLDER%/bardsong/c0bardsx.spl~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Bard Song Ready~) END
COPY ~%MOD_FOLDER%/bardsong/c0brdef1.bam~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0brdef1.vvc~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0bardso.wav~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singin.eff~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singin.spl~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Singing Bard Song~) END
COPY ~%MOD_FOLDER%/bardsong/c0singi2.eff~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singi2.spl~ OVERRIDE
COPY ~%MOD_FOLDER%/bardsong/c0singi2.spl~ OVERRIDE

ACTION_IF FILE_EXISTS_IN_GAME ~C0BWHL8.spl~ THEN BEGIN
COPY_EXISTING ~C0BWHL3.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL4.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL5.SPL~ ~OVERRIDE~
WRITE_BYTE 0x1c 5
COPY_EXISTING ~C0BWHL8.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 99 parameter1 = 130 END
END

COPY_EXISTING_REGEXP GLOB ~.*\.spl~ ~override~
  PATCH_IF (BUFFER_LENGTH > 0x71) THEN BEGIN
  SPRINT bardsong_name ~%SOURCE_RES%~
  SET patch_bard_song = 0
  SET no_patch = 0
  READ_BYTE 0x1c spell_type
    READ_LONG  0x64 ___#abil_off
    READ_SHORT 0x68 ___#abil_num
    READ_LONG  0x6a ___#fx_off
				 FOR (___#index1 = 0 ; ___#index1 < ___#abil_num ; ___#index1 = ___#index1 + 1) BEGIN
				READ_SHORT (___#abil_off + 0x1e + (0x28 * ___#index1)) ___#abil_fx_num
        READ_SHORT (___#abil_off + 0x20 + (0x28 * ___#index1)) ___#abil_fx_idx
          FOR (___#index2 = ___#abil_fx_idx ; ___#index2 < (___#abil_fx_idx + ___#abil_fx_num) ; ___#index2 = ___#index2 + 1) BEGIN
            READ_SHORT (___#fx_off + 0x30 * ___#index2) ___#opcode
            READ_SHORT (___#fx_off + 0x30 * ___#index2 + 0x02) ___#target
            READ_SHORT (___#fx_off + 0x30 * ___#index2 + 0x08) ___#param2
            
	  PATCH_IF  (spell_type = 5) AND ((___#opcode = 126) AND (___#target = 1)) AND !(patch_bard_song = 1) BEGIN
              SET no_patch = 1
              SET patch_bard_song = 1
            END
    END
    END
    END
		FOR (___#index1 = 0 ; ___#index1 < ___#abil_num ; ___#index1 = ___#index1 + 1) BEGIN
				READ_SHORT (___#abil_off + 0x1e + (0x28 * ___#index1)) ___#abil_fx_num
        READ_SHORT (___#abil_off + 0x20 + (0x28 * ___#index1)) ___#abil_fx_idx
          FOR (___#index2 = ___#abil_fx_idx ; ___#index2 < (___#abil_fx_idx + ___#abil_fx_num) ; ___#index2 = ___#index2 + 1) BEGIN
            READ_SHORT (___#fx_off + 0x30 * ___#index2) ___#opcode
            READ_SHORT (___#fx_off + 0x30 * ___#index2 + 0x02) ___#target
            READ_SHORT (___#fx_off + 0x30 * ___#index2 + 0x08) ___#param2
            
	  PATCH_IF  (spell_type = 5) AND ((___#opcode = 142) AND (___#param2 = 40)) AND !(patch_bard_song = 1) AND !(no_patch = 1) BEGIN
            INNER_ACTION BEGIN
            PRINT ~%bardsong_name% is a bard song.~
            END
              SET patch_bard_song = 1

    LPF GET_UNIQUE_FILE_NAME STR_VAR extension = "SPL" base = EVAL "%bardsong_name%" RET song_name = filename END
    INNER_PATCH_SAVE song_name "%song_name%" BEGIN REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH ~__~ ~C0BW~ END

    INNER_ACTION BEGIN
    
    COPY_EXISTING ~%bardsong_name%.spl~ ~override/%song_name%.spl~
    COPY ~%MOD_FOLDER%/bardsong/c0bardso.spl~ ~OVERRIDE/%bardsong_name%.SPL~
    LPF ALTER_SPELL_HEADER INT_VAR projectile = c0bardso END
    LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = BARDSONG resource = EVAL ~%bardsong_name%~ END

    COPY ~%MOD_FOLDER%/bardsong/c0bardso.eff~ ~OVERRIDE/%bardsong_name%.EFF~
    WRITE_ASCIIE 0x30 ~%song_name%~
    END
    END
    END
    END
    BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//bard

        PATCH_IF "%row_name%" STRING_EQUAL_CASE "BARD" BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_BARD_eff ~While active, the Bard Song has the following effects:
  Restore morale to its average value
  Remove Fear
  Protection From Fear~
          SPRINT new_BARD_eff ~While active, the Bard Song has the following effects, improving with level:
  1st level: +1 Luck, immunity to fear and morale failure
  15th level: +2 Luck, immunity to fear and morale failure
  20th level: +3 Luck, immunity to fear and morale failure
~
          SPRINT old_BARD ~– May use Bard Song ability.~
          SPRINT new_BARD ~BARD SONG: The Bard's Song may be used an unlimited number of times, and lasts for 6 rounds + 1 round per 5 levels gained. The Bard Song has a cooldown of 1 turn before it may be used again.~
          GET_STRREF %kit_desc% desc_text
          INNER_PATCH_SAVE desc_text ~%desc_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_BARD_eff%~ ~%new_BARD_eff%~
            REPLACE_TEXTUALLY ~%old_BARD%~ ~%old_BARD%
            
%new_BARD%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%desc_text%~)
            PRETTY_PRINT_2DA
		END
		
      END
      BUT_ONLY
    END
  END

COPY_EXISTING ~enginest.2da~ ~override~
  COUNT_2DA_ROWS 2 rows
  FOR (row = 0 ; row < rows ; ++row) BEGIN
    READ_2DA_ENTRY row 0 2 entry
    PATCH_IF (("%entry%" STRING_COMPARE_CASE "STRREF_FEEDBACK_BATTLESONGBEGIN"      = 0) OR
              ("%entry%" STRING_COMPARE_CASE "STRREF_FEEDBACK_BATTLESONGEND"   		= 0)) BEGIN
      FOR (col = 1; col < 2 ; ++col) BEGIN
        SET_2DA_ENTRY row col 2 0
      END
    END
  END
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all spell files
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 200 parameter1 = 110 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 300 parameter1 = 120 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 400 parameter1 = 130 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 500 parameter1 = 140 END
LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 99 match_parameter2 = 2 match_parameter1 = 600 parameter1 = 150 END
BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~^.+\.bcs~ ~override~ //Parse through all dlg files
                DECOMPILE_AND_PATCH BEGIN
                    REPLACE_TEXTUALLY ~!ModalState(BATTLESONG)~ ~!CheckSpellState(Myself,BARD_SONG)~ //Replace trigger respecting OR and !
                END
                DECOMPILE_AND_PATCH BEGIN
                    //Recommended by refactor trigger to fix whitespace
                END

        BUT_ONLY
        