COPY ~%MOD_FOLDER%/Kapellmeister/2das~ ~override~
COPY ~%MOD_FOLDER%/Kapellmeister/spells~ ~override~


LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 5
	
    mixed         = RESOLVE_STR_REF(~Kapellmeister~)
	
    lower         = RESOLVE_STR_REF(~kapellmeister~)
	
    help          = RESOLVE_STR_REF(~KAPELLMEISTER: This bard is a specialist of magical theory, skilled at conducting and supporting other arcanists in the battlefield through empowering their spells. They are often found in command of battalions of wizards, at the lead with their baton in hand, and are no less capable at the use of magic themselves when necessary. 

Advantages:
– May cast two additional spells per level.
– The Kapellmeister's Bard Song, "Symphonie", bolsters the memory and concentration of allied mages, enhancing their Intelligence and Casting Level as well as granting a chance to restore their spells. Lower level spells have a higher chance of being restored than high level spells.
  1st level: +1 to Intelligence and Arcane Casting Level, 10% chance to restore one arcane spell of up to 4th level each round.
  10th level: +2 to Intelligence and Arcane Casting Level, +1 to Casting Speed, 15% chance to restore one arcane spell of up to 6th level each round.
  15th level: +2 to Intelligence and Arcane Casting Level, +2 to Casting Speed, 15% chance to restore one arcane spell of up to 6th level each round
  20th level: +3 to Intelligence and Arcane Casting Level, +2 to Casting Speed, 25% chance to restore one arcane spell of up to 8th level each round

– 3rd level: Gains the Magical Cadence passive effect.

MAGICAL CADENCE: On every 5th round, the Kapellmeister gains a +4 bonus to casting level, and casting time of spells is reduced to 1, if higher, for one round.

– 9th level: Extend Spell: The Kapellmeister's arcane spells have an increased duration of 20%. Half of this value is granted to allies while singing.
– 10th level: Magical Cadence now applies on every 4th round.
– 17th level: Magical Cadence now applies on every 3rd round.
– 22nd level: Persistent Spell: The Kapellmeister's arcane spells have an increased duration of 50%, replacing the Extend Spell bonus. Half of this value is granted to allies while singing.

Disadvantages:
– THAC0 progresses as that of a Mage of the same level.
– Only has one quarter the normal Pick Pockets skill.~)
	
    briefdesc     = RESOLVE_STR_REF(~KAPELLMEISTER: This bard is a specialist of magical theory, skilled at conducting and supporting other arcanists in the battlefield through empowering their spells. They are often found in command of battalions of wizards, at the lead with their baton in hand, and are no less capable at the use of magic themselves when necessary.~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0_KAPELLMEISTER~
	
    unusable      = ~0x00000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 3~
	
    abclasrq      = ~0 12 0 16 0 12~
	
    // abclsmod      = ~-2 0 -2 0 0 -4~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 0 0 0 1 1 0 0 0~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0KAPL~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0KAPEL.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    clascolr = ~24 25 190 21 83~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~25 0 0 0 0 0 0 0~
	
	// backstab = ~1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
	
	// sneakatt = ~1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 6~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Magical Cadence (Active)~) STR_VAR bam_file = C0KM#01I RET C0KM#01I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Magical Cadence (Inactive)~) STR_VAR bam_file = C0KM#01N RET C0KM#01N = icon END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#S0.spl~ ~override~
SAY NAME1 ~Symphonie~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#SO3.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~One Spell Restored~) END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#SO4.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Two Spells Restored~) END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#01A.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_timing = 0 parameter2 = C0KM#01I END
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_timing = 4 parameter2 = C0KM#01N END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H1.spl~ ~override~
SAY NAME1 ~Extra Level 1-3 Spell~
SAY UNIDENTIFIED_DESC ~Choosing this ability allows the Kapellmeister to cast one additional Level 1, 2 and 3 spell.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H2.spl~ ~override~
SAY NAME1 ~Extra Level 4-6 Spell~
SAY UNIDENTIFIED_DESC ~Choosing this ability allows the Kapellmeister to cast one additional Level 4, 5 and 6 spell.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H3.spl~ ~override~
SAY NAME1 ~Song of Universal Harmony~
SAY UNIDENTIFIED_DESC ~This ability allows the Kapellmeister to cast any 1st to 9th level arcane spell of their choosing. After using the ability, any spell may be selected and cast as though a mage spell of the Kapellmeister's level. However, upon starting the song, the Kapellmeister becomes unable to sing, cast spells or use special abilities for the following two rounds.

Song of Universal Harmony may be selected up to five times.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H4.spl~ ~override~
SAY NAME1 ~Die Aufklärung~
SAY UNIDENTIFIED_DESC ~This song is a powerful aid to the Kapellmeister and to any of their allied spellcasters. Die Aufklärung grants the Kapellmeister themselves a 10-point bonus to Saving Throws vs. Spells and a 50% bonus to Magic Resistance due to the power of the song. The song also gives the Kapellmeister's allies a +4 bonus to Intelligence and Arcane Casting Level, +2 bonus to Casting Speed, and two rolls for a 30% chance to restore an arcane spell of up to 8th level each round.

This ability replaces the current Bard Song.~
