COPY ~%MOD_FOLDER%/Kapellmeister/2das~ ~override~
COPY ~%MOD_FOLDER%/Kapellmeister/spells~ ~override~
/*
ACTION_IF NOT FILE_EXISTS_IN_GAME ~C0A_A01.SPL~ BEGIN
INCLUDE ~%MOD_FOLDER%/LIB/ANALYZE.TPA~
END
*/
ADD_KIT ~C0_KAPELLMEISTER~

 // appended to CLASWEAP.2da
 ~C0_KAPELLMEISTER		1           1           1           1           1           1           1           1~

 // appended column-wise to WEAPPROF.2da
//11                   		                 		T   S           F   Q             S S
//10                  	                 			W   C           L   U             W I
//9                   	     			    B L S   O   I   W       A   A             O N
//8                  	      				A O H   H   M   A       I   R C   S       R G
//7         				L S           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6         				_ _       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5         				S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4         				W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3         				O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2        					R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1      	  				D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
 ~C0_KAPELLMEISTER			1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
    
 // appended to ABCLASRQ.2da
 ~C0_KAPELLMEISTER				0	12	0	16	0	15~

 // appended to ABCLSMOD.2da
 ~C0_KAPELLMEISTER				0	0	0	0	0	0~

 // appended to ABDCDSRQ.2da
 ~C0_KAPELLMEISTER				0	0	0	0	0	0~

 // appended to ABDCSCRQ.2da
 ~C0_KAPELLMEISTER				0	0	0	0	0	0~

 // appended to ALIGNMNT.2da
 ~C0_KAPELLMEISTER				0	0	0	1	1	1	1	1	1~

 // appended to DUALCLAS.2da
 ~C0_KAPELLMEISTER				0	0	0	0	0	0~

 // path to your CLAB-style 2da file 
 ~override/C0KAPEL.2da~

 // PC races and classes allowed to use this kit, from KITTABLE.2da
 ~K_B_H K_B_E K_B_HE K_B_HL K_B_G K_B_D K_B_HO~

 // usability flags, added to the end of the KITLIST.2da entry
 ~0x00004000     5~

 // HLA table to use; see LUABBR.2da
 ~C0KAPL~

 // list of starting equipment for PCs starting in ToB. Appended column-wise to 25STWEAP.2da
 ~CHAN12 * * BAG30 RING06 RING34 CLCK02 BOOT01 AMUL19 BRAC16 BELT10 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 DAGG12 SW1H28 STAF08~

 // Lower, mixed, and help kit names and descriptions, added to KITLIST.2da
  SAY ~kapellmeister~
  SAY ~Kapellmeister~
  SAY ~KAPELLMEISTER: This bard is a specialist of magical theory, skilled at conducting and supporting other arcanists in the battlefield through empowering their spells. They are often found in command of battalions of wizards, at the lead with their baton in hand, and are no less capable at the use of magic themselves when necessary. 

Advantages:
– May cast two additional spells per level.
– The Kapellmeister's Bard Song, "Symphonie", bolsters the memory and concentration of allied mages, enhancing their Intelligence and Casting Level as well as granting a chance to restore their spells. 
  1st level: +1 to Intelligence and Arcane Casting Level, 15% chance to restore one arcane spell of up to 3rd level each round.
  10th level: +2 to Intelligence and Arcane Casting Level, 15% chance to restore one arcane spell of up to 5th level each round.
  15th level: +2 to Intelligence and Arcane Casting Level, +1 to Casting Speed, 30% chance to restore one arcane spell of up to 5th level each round
  20th level: +3 to Intelligence and Arcane Casting Level, +1 to Casting Speed, 30% chance to restore one arcane spell of up to 8th level each round

– 3rd level: Gains the Magical Cadence passive effect.

MAGICAL CADENCE: On every 5th round, the Kapellmeister gains a +4 bonus to casting level, and casting time of spells is reduced to 1, if higher, for one round.

– 9th level: Extend Spell: The Kapellmeister's arcane spells have an increased duration of 20%. Half of this value is granted to allies while singing.
– 10th level: Magical Cadence now applies on every 4th round.
– 17th level: Magical Cadence now applies on every 3rd round.
– 22nd level: Persistent Spell: The Kapellmeister's arcane spells have an increased duration of 50%, replacing the Extend Spell bonus. Half of this value is granted to allies while singing.

Disadvantages:
– THAC0 progresses as that of a Mage of the same level.
– Only has one quarter the normal Pick Pockets skill.~

LAF fl#add_kit_ee
  STR_VAR
    kit_name = C0_KAPELLMEISTER
	clascolr = ~24 25 190 21 83~ // METAL MINOR MAJOR LEATHER ARMOR
	thiefscl = ~25 0 0 0 0 0 0 0~
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Magical Cadence (Active)~) STR_VAR bam_file = C0KM#01I RET C0KM#01I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Magical Cadence (Inactive)~) STR_VAR bam_file = C0KM#01N RET C0KM#01N = icon END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#S0.spl~ ~override~
SAY NAME1 ~Symphonie~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#SO3.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~One Spell Restored~) END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#SO4.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Two Spells Restored~) END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#01A.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_timing = 0 parameter2 = C0KM#01I END
LPF ALTER_EFFECT INT_VAR match_opcode = 142 match_timing = 4 parameter2 = C0KM#01N END

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H1.spl~ ~override~
SAY NAME1 ~Extra Level 1-3 Spell~
SAY UNIDENTIFIED_DESC ~Choosing this ability allows the Kapellmeister to cast one additional Level 1, 2 and 3 spell.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H2.spl~ ~override~
SAY NAME1 ~Extra Level 4-6 Spell~
SAY UNIDENTIFIED_DESC ~Choosing this ability allows the Kapellmeister to cast one additional Level 4, 5 and 6 spell.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H3.spl~ ~override~
SAY NAME1 ~Song of Universal Harmony~
SAY UNIDENTIFIED_DESC ~This ability allows the Kapellmeister to cast any 1st to 9th level arcane spell of their choosing. After using the ability, any spell may be selected and cast as though a mage spell of the Kapellmeister's level. However, upon starting the song, the Kapellmeister becomes unable to sing, cast spells or use special abilities for the following two rounds.

Song of Universal Harmony may be selected up to five times.~

COPY ~%MOD_FOLDER%/Kapellmeister/spells/C0KM#H4.spl~ ~override~
SAY NAME1 ~Die Aufklärung~
SAY UNIDENTIFIED_DESC ~This song is a powerful aid to the Kapellmeister and to any of their allied spellcasters. Die Aufklärung grants the Kapellmeister themselves a 10-point bonus to Saving Throws vs. Spells and a 50% bonus to Magic Resistance due to the power of the song. The song also gives the Kapellmeister's allies a +4 bonus to Intelligence and Arcane Casting Level, +2 bonus to Casting Speed, and two rolls for a 30% chance to restore an arcane spell of up to 8th level each round.

This ability replaces the current Bard Song.~
